nome=input("Digite uma palavra de 5 letras")
if len(nome)==5:
    print("Palavra com 5 letras!")
else:
    print("Palavra não tem 5 letras!")
print(nome[0])
print()
print(nome[1])
print()
print(nome[2])
print()
print(nome[3])
print()
print(nome[4])
print()
print(nome[2:5])
print()
print(nome[-2])
print()
print(nome[::-1])